// ═══════════════════════════════════════════════════════════════
// APOTHEOS COURSE CATALOGUE — canonical source of truth
// Pulled from curriculum.html and calendar.html event data
// rotation_week: null = runs every week | 0-5 = runs in that rotation
// ═══════════════════════════════════════════════════════════════

export type TrackName = 'wellness' | 'ai' | 'founder' | 'community'

export interface CourseData {
  slug: string
  name: string
  description: string
  track: TrackName
  duration_min: number
  rotation_week: number | null
  day_of_week: string
  start_time: string
  space: string
  instructor: string
  capacity: number
  objectives: string[]
  outline: CourseWeekOutline[]
}

export interface CourseWeekOutline {
  week?: number
  title: string
  description: string
}

// ─── WELLNESS TRACK ──────────────────────────────────────────
const wellnessCourses: CourseData[] = [
  {
    slug: 'morning-yoga-flow',
    name: 'Morning Yoga Flow',
    description: 'A vinyasa-based morning flow to activate the body, center the mind, and set intention for the day. All levels welcome.',
    track: 'wellness',
    duration_min: 60,
    rotation_week: null,
    day_of_week: 'mon',
    start_time: '07:00',
    space: 'Movement Studio',
    instructor: 'Apotheos Wellness Team',
    capacity: 20,
    objectives: [
      'Build a consistent morning movement practice',
      'Develop body awareness and breath control',
      'Cultivate mental clarity through embodied presence',
    ],
    outline: [
      { title: 'Foundation', description: 'Breath work, centering, intention setting, sun salutations' },
      { title: 'Activation', description: 'Standing sequences, balance poses, core engagement' },
      { title: 'Integration', description: 'Hip openers, inversions, restorative poses, savasana' },
    ],
  },
  {
    slug: 'breathwork-meditation',
    name: 'Breathwork & Meditation',
    description: 'Guided breathwork techniques (box, 4-7-8, holotropic) followed by silent or guided meditation. Drop-in anytime.',
    track: 'wellness',
    duration_min: 60,
    rotation_week: null,
    day_of_week: 'tue',
    start_time: '07:00',
    space: 'Meditation Room',
    instructor: 'Apotheos Wellness Team',
    capacity: 15,
    objectives: [
      'Master foundational breathwork techniques',
      'Reduce stress and regulate the nervous system',
      'Develop a sustainable daily meditation habit',
    ],
    outline: [
      { title: 'Theory', description: 'Breath science, nervous system basics, intention' },
      { title: 'Practice', description: 'Sequential breathwork protocols, guided meditation' },
      { title: 'Integration', description: 'Journaling prompts, accountability structures' },
    ],
  },
  {
    slug: 'movement-lab',
    name: 'Movement Lab',
    description: 'Functional movement, mobility work, and somatic practices drawn from martial arts, dance, and physical therapy traditions.',
    track: 'wellness',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'wed',
    start_time: '07:30',
    space: 'Movement Studio',
    instructor: 'Apotheos Wellness Team',
    capacity: 18,
    objectives: [
      'Identify and address personal movement patterns and restrictions',
      'Build resilient, functional strength and mobility',
      'Integrate body-awareness across all life activities',
    ],
    outline: [
      { title: 'Assessment', description: 'Movement screen, mobility baseline, personal goals' },
      { title: 'Foundation', description: 'Core primitives — hinge, squat, carry, crawl' },
      { title: 'Exploration', description: 'Play-based exploration, partner work, feedback loops' },
    ],
  },
  {
    slug: 'nutrition-optimization',
    name: 'Nutrition Optimization',
    description: 'Evidence-based nutrition for high-performers: metabolic health, meal timing, supplementation, and food as medicine.',
    track: 'wellness',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'thu',
    start_time: '08:00',
    space: 'Workshop Space',
    instructor: 'Apotheos Wellness Team',
    capacity: 25,
    objectives: [
      'Understand personal metabolic needs and macro ratios',
      'Build an anti-inflammatory, performance-focused diet',
      'Create sustainable meal-prep habits',
    ],
    outline: [
      { title: 'Foundations', description: 'Macros, micros, metabolic rate, food quality hierarchy' },
      { title: 'Strategies', description: 'Meal timing, intermittent fasting, practical planning' },
      { title: 'Advanced', description: 'Supplementation, gut health, personalised protocols' },
    ],
  },
  {
    slug: 'recovery-sleep-science',
    name: 'Recovery & Sleep Science',
    description: 'The science of sleep and active recovery — circadian rhythms, HRV, ice baths, sauna protocols, and performance.',
    track: 'wellness',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'fri',
    start_time: '08:00',
    space: 'Workshop Space',
    instructor: 'Apotheos Wellness Team',
    capacity: 25,
    objectives: [
      'Optimise sleep quality and circadian alignment',
      'Design a weekly recovery protocol using available modalities',
      'Track and interpret HRV and sleep metrics',
    ],
    outline: [
      { title: 'Sleep Science', description: 'Stages, circadian biology, common disruptors' },
      { title: 'Active Recovery', description: 'Cold/heat therapy, breathwork, massage modalities' },
      { title: 'Protocol Design', description: 'Building your personal recovery stack' },
    ],
  },
  {
    slug: 'holistic-health-seminar',
    name: 'Holistic Health Seminar',
    description: 'Monthly deep-dive speakers covering integrative medicine, longevity, functional health, and cutting-edge wellness research.',
    track: 'wellness',
    duration_min: 120,
    rotation_week: null,
    day_of_week: 'sat',
    start_time: '09:00',
    space: 'Event Hall',
    instructor: 'Guest Speakers',
    capacity: 60,
    objectives: [
      'Gain exposure to frontier wellness and longevity research',
      'Build a network of health-conscious practitioners',
      'Identify action items for immediate health improvement',
    ],
    outline: [
      { title: 'Keynote', description: 'Guest expert presentation (75 min)' },
      { title: 'Q&A', description: 'Community discussion and Q&A (30 min)' },
      { title: 'Integration', description: 'Action planning, resource sharing (15 min)' },
    ],
  },
  {
    slug: 'kids-yoga-mindfulness',
    name: 'Kids Yoga & Mindfulness',
    description: 'Age-appropriate yoga, breathwork, and mindfulness for children ages 6–14. Builds emotional regulation and body awareness.',
    track: 'wellness',
    duration_min: 60,
    rotation_week: null,
    day_of_week: 'mon',
    start_time: '16:00',
    space: 'Movement Studio',
    instructor: 'Apotheos Wellness Team',
    capacity: 15,
    objectives: [
      'Introduce mindful movement in a fun, age-appropriate way',
      'Develop early emotional regulation skills',
      'Build body confidence and coordination',
    ],
    outline: [
      { title: 'Warm-Up', description: 'Animal poses, games, breathing exercises' },
      { title: 'Flow', description: 'Storytelling yoga sequences' },
      { title: 'Cool-Down', description: 'Relaxation, gratitude circle' },
    ],
  },
  {
    slug: 'family-fitness',
    name: 'Family Fitness',
    description: 'Saturday family workout — fun circuits, team challenges, and movement games for kids and adults together.',
    track: 'wellness',
    duration_min: 60,
    rotation_week: null,
    day_of_week: 'sat',
    start_time: '11:00',
    space: 'Movement Studio',
    instructor: 'Apotheos Wellness Team',
    capacity: 30,
    objectives: [
      'Make movement a family habit',
      'Build teamwork and shared identity around fitness',
      'Introduce kids to functional movement',
    ],
    outline: [
      { title: 'Warm-Up Games', description: 'Group tag, movement challenges' },
      { title: 'Circuit', description: 'Station-based family workout' },
      { title: 'Cool-Down', description: 'Partner stretching, family celebration' },
    ],
  },
]

// ─── AI LEARNING TRACK ───────────────────────────────────────
const aiCourses: CourseData[] = [
  {
    slug: 'ai-fundamentals',
    name: 'AI Fundamentals for Non-Technical Leaders',
    description: 'Demystify AI for business: machine learning basics, large language models, computer vision, and how to evaluate AI tools.',
    track: 'ai',
    duration_min: 120,
    rotation_week: 0,
    day_of_week: 'mon',
    start_time: '13:00',
    space: 'Tech Lab',
    instructor: 'Apotheos AI Team',
    capacity: 25,
    objectives: [
      'Explain how machine learning and LLMs work at a conceptual level',
      'Evaluate AI tools and vendors without a technical background',
      'Identify the top 3 AI opportunities in your business',
    ],
    outline: [
      { week: 1, title: 'What Is AI?', description: 'Types of ML, history, hype vs. reality' },
      { week: 2, title: 'Language Models', description: 'How LLMs work, prompting strategies' },
      { week: 3, title: 'Computer Vision & Audio', description: 'Real-world perception AI' },
      { week: 4, title: 'AI in Your Industry', description: 'Case studies and opportunity mapping' },
      { week: 5, title: 'Evaluating Tools', description: 'ROI, vendor vetting, red flags' },
      { week: 6, title: 'AI Strategy Deck', description: 'Build and present your AI roadmap' },
    ],
  },
  {
    slug: 'prompt-engineering',
    name: 'Prompt Engineering Mastery',
    description: 'Go from basic prompts to advanced techniques: chain-of-thought, few-shot, RAG patterns, and multi-step agent workflows.',
    track: 'ai',
    duration_min: 120,
    rotation_week: 1,
    day_of_week: 'tue',
    start_time: '13:00',
    space: 'Tech Lab',
    instructor: 'Apotheos AI Team',
    capacity: 20,
    objectives: [
      'Write prompts that consistently produce high-quality outputs',
      'Apply chain-of-thought and few-shot techniques',
      'Build multi-step prompt pipelines for complex tasks',
    ],
    outline: [
      { week: 1, title: 'Prompt Anatomy', description: 'System, user, assistant roles; temperature and tokens' },
      { week: 2, title: 'Advanced Techniques', description: 'Chain-of-thought, tree-of-thought, self-consistency' },
      { week: 3, title: 'Few-Shot & RAG', description: 'In-context learning, retrieval augmented generation' },
      { week: 4, title: 'Agent Patterns', description: 'Tool use, function calling, memory' },
      { week: 5, title: 'Domain Specialization', description: 'Prompts for legal, finance, marketing, code' },
      { week: 6, title: 'Capstone', description: 'Build an automated prompt pipeline for your use case' },
    ],
  },
  {
    slug: 'ai-automation-workflows',
    name: 'AI Automation & Workflows',
    description: 'Build no-code and low-code AI automations using Make, Zapier, n8n, and the OpenAI/Anthropic APIs. Ship in hours, not weeks.',
    track: 'ai',
    duration_min: 120,
    rotation_week: 2,
    day_of_week: 'wed',
    start_time: '13:00',
    space: 'Tech Lab',
    instructor: 'Apotheos AI Team',
    capacity: 20,
    objectives: [
      'Map and automate at least one business process end-to-end',
      'Connect AI APIs to real-world tools using Make/n8n',
      'Estimate time-savings and ROI for your automations',
    ],
    outline: [
      { week: 1, title: 'Automation Thinking', description: 'Process mapping, trigger-action logic' },
      { week: 2, title: 'No-Code Tools', description: 'Make.com, Zapier, N8N overview and hands-on' },
      { week: 3, title: 'API Basics', description: 'REST APIs, authentication, postman, JSON' },
      { week: 4, title: 'AI APIs', description: 'OpenAI, Anthropic — calling them in workflows' },
      { week: 5, title: 'Complex Automations', description: 'Multi-step, branching, error handling' },
      { week: 6, title: 'Ship Your Automation', description: 'Live demo of student automations' },
    ],
  },
  {
    slug: 'ai-business-model',
    name: 'AI Business Model Playbook',
    description: 'Revenue models, pricing strategies, and go-to-market playbooks built specifically for AI-native products and services.',
    track: 'ai',
    duration_min: 120,
    rotation_week: 3,
    day_of_week: 'mon',
    start_time: '14:00',
    space: 'Parlour',
    instructor: 'Apotheos AI Team',
    capacity: 20,
    objectives: [
      'Design a sustainable revenue model for an AI product',
      'Build an AI-native go-to-market playbook',
      'Identify and defend your competitive moat',
    ],
    outline: [
      { week: 1, title: 'AI Business Models', description: 'API wrappers, co-pilots, fully autonomous agents, platforms' },
      { week: 2, title: 'Pricing', description: 'Per-seat vs. usage, freemium, enterprise' },
      { week: 3, title: 'Distribution', description: 'SEO, community, partnerships, influencer' },
      { week: 4, title: 'Defensibility', description: 'Data moats, workflow lock-in, brand' },
      { week: 5, title: 'Fundraising', description: 'AI investment thesis, due diligence red flags' },
      { week: 6, title: 'Pitch Day', description: 'Present your AI business model to the cohort' },
    ],
  },
  {
    slug: 'machine-learning-applications',
    name: 'Applied Machine Learning',
    description: 'Hands-on ML for practitioners: scikit-learn, fine-tuning, embeddings, vector databases, and building your first ML pipeline.',
    track: 'ai',
    duration_min: 120,
    rotation_week: 4,
    day_of_week: 'tue',
    start_time: '14:00',
    space: 'Tech Lab',
    instructor: 'Apotheos AI Team',
    capacity: 15,
    objectives: [
      'Understand and apply core ML algorithms (classification, regression, clustering)',
      'Build an end-to-end ML pipeline from data to deployment',
      'Fine-tune a pre-trained model on a custom dataset',
    ],
    outline: [
      { week: 1, title: 'ML Fundamentals', description: 'Train/test split, overfitting, evaluation metrics' },
      { week: 2, title: 'Classification', description: 'Logistic regression, decision trees, random forests' },
      { week: 3, title: 'Embeddings', description: 'Vector representations, semantic search, cosine similarity' },
      { week: 4, title: 'Fine-Tuning', description: 'When and how to fine-tune; LoRA and PEFT methods' },
      { week: 5, title: 'ML in Production', description: 'MLflow, monitoring, drift detection' },
      { week: 6, title: 'Capstone', description: 'End-to-end ML project presentation' },
    ],
  },
  {
    slug: 'data-strategy-analytics',
    name: 'Data Strategy & Analytics',
    description: 'Turn raw data into strategic assets: dashboards, KPIs, data pipelines, and building a data-driven culture in your org.',
    track: 'ai',
    duration_min: 120,
    rotation_week: 5,
    day_of_week: 'wed',
    start_time: '14:00',
    space: 'Tech Lab',
    instructor: 'Apotheos AI Team',
    capacity: 20,
    objectives: [
      'Define and instrument the 5 most important KPIs for your business',
      'Build a live dashboard connected to real data sources',
      'Design a data governance framework for your team',
    ],
    outline: [
      { week: 1, title: 'Data Strategy Foundations', description: 'First-party data, data moats, quality vs. quantity' },
      { week: 2, title: 'KPI Design', description: 'Choosing metrics that matter; leading vs. lagging indicators' },
      { week: 3, title: 'Data Pipelines', description: 'ETL, dbt, Airbyte — moving and transforming data' },
      { week: 4, title: 'Dashboards', description: 'Metabase, Tableau, Looker — hands-on build' },
      { week: 5, title: 'Analytics Culture', description: 'Self-serve analytics, data literacy across the org' },
      { week: 6, title: 'Capstone', description: 'Present a data strategy and live dashboard to the cohort' },
    ],
  },
  {
    slug: 'kids-coding-python',
    name: 'Kids Coding: Python & AI',
    description: 'Introduction to Python programming for ages 10–16. Projects include games, chatbots, and simple machine learning experiments.',
    track: 'ai',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'tue',
    start_time: '16:00',
    space: 'Tech Lab',
    instructor: 'Apotheos AI Team',
    capacity: 12,
    objectives: [
      'Write and run basic Python programs',
      'Build a simple chatbot using an AI API',
      'Develop computational thinking and problem-solving',
    ],
    outline: [
      { title: 'Python Basics', description: 'Variables, loops, functions — turtle graphics, simple games' },
      { title: 'APIs & AI', description: 'Connecting to an AI API, building a chatbot' },
      { title: 'Project', description: 'Students present their own Python project' },
    ],
  },
]

// ─── FOUNDER ECOSYSTEM TRACK ──────────────────────────────────
const founderCourses: CourseData[] = [
  {
    slug: 'startup-fundamentals',
    name: 'Startup Fundamentals',
    description: 'The end-to-end playbook for founders: ideation, validation, MVP, fundraising, team building, and scaling. Built for early-stage.',
    track: 'founder',
    duration_min: 120,
    rotation_week: 0,
    day_of_week: 'tue',
    start_time: '13:00',
    space: 'Showroom',
    instructor: 'Apotheos Founder Team',
    capacity: 25,
    objectives: [
      'Validate a business idea using the Lean Startup framework',
      'Build and ship a minimum viable product in 6 weeks',
      'Pitch your company to investors',
    ],
    outline: [
      { week: 1, title: 'Ideation & Problem', description: 'Jobs-to-be-done, pain points, opportunity mapping' },
      { week: 2, title: 'Validation', description: 'Customer discovery interviews, smoke tests' },
      { week: 3, title: 'MVP Design', description: 'Scope reduction, prototype, first users' },
      { week: 4, title: 'Growth', description: 'Distribution channels, product-market fit signals' },
      { week: 5, title: 'Fundraising 101', description: 'Pre-seed, seed, angels, SAFEs, terms' },
      { week: 6, title: 'Demo Day', description: 'Pitch to cohort and invited investors' },
    ],
  },
  {
    slug: 'product-strategy',
    name: 'Product Strategy & Roadmapping',
    description: 'Build products people love: user research, prioritization frameworks, OKRs, roadmap design, and cross-functional alignment.',
    track: 'founder',
    duration_min: 120,
    rotation_week: 1,
    day_of_week: 'wed',
    start_time: '13:00',
    space: 'Showroom',
    instructor: 'Apotheos Founder Team',
    capacity: 20,
    objectives: [
      'Run a professional user research process from scratch',
      'Build and defend a 6-month product roadmap',
      'Align stakeholders using OKRs and product strategy documents',
    ],
    outline: [
      { week: 1, title: 'Product Thinking', description: 'Outcome vs. output, the product mindset' },
      { week: 2, title: 'User Research', description: 'Interviews, surveys, usability testing' },
      { week: 3, title: 'Prioritization', description: 'RICE, ICE, MoSCoW, opportunity scoring' },
      { week: 4, title: 'Roadmapping', description: 'Theme-based roadmaps, now/next/later' },
      { week: 5, title: 'OKRs & Alignment', description: 'Setting goals, cross-functional sync' },
      { week: 6, title: 'Roadmap Presentation', description: 'Present product strategy to a mock board' },
    ],
  },
  {
    slug: 'growth-marketing',
    name: 'Growth Marketing & Distribution',
    description: 'Modern growth: SEO, paid ads, email, content marketing, community, and building a full-funnel acquisition machine.',
    track: 'founder',
    duration_min: 120,
    rotation_week: 2,
    day_of_week: 'thu',
    start_time: '13:00',
    space: 'Showroom',
    instructor: 'Apotheos Founder Team',
    capacity: 25,
    objectives: [
      'Build a full-funnel marketing strategy from awareness to conversion',
      'Run and optimise at least one paid acquisition channel',
      'Create a 90-day growth plan with measurable targets',
    ],
    outline: [
      { week: 1, title: 'Growth Fundamentals', description: 'Funnel thinking, ICPs, channel selection' },
      { week: 2, title: 'Content & SEO', description: 'Keyword strategy, content types, distribution' },
      { week: 3, title: 'Paid Acquisition', description: 'Meta, Google, LinkedIn — ad creation and optimisation' },
      { week: 4, title: 'Email & Retention', description: 'Lifecycle sequences, segmentation, deliverability' },
      { week: 5, title: 'Community & Viral', description: 'Referral loops, community-led growth' },
      { week: 6, title: 'Growth Plan Presentation', description: 'Present 90-day growth plan to peers' },
    ],
  },
  {
    slug: 'fundraising-investor-relations',
    name: 'Fundraising & Investor Relations',
    description: 'Navigate the VC landscape: deck design, term sheets, due diligence, cap table management, and long-term investor relations.',
    track: 'founder',
    duration_min: 120,
    rotation_week: 3,
    day_of_week: 'tue',
    start_time: '13:00',
    space: 'Showroom',
    instructor: 'Apotheos Founder Team',
    capacity: 20,
    objectives: [
      'Create a compelling fundraising deck and narrative',
      'Understand and negotiate term sheets and SAFEs',
      'Build a strategic investor pipeline',
    ],
    outline: [
      { week: 1, title: 'Funding Landscape', description: 'Bootstrapping, angels, seed, Series A — what investors look for' },
      { week: 2, title: 'The Deck', description: 'Story structure, design principles, investor red flags' },
      { week: 3, title: 'The Ask', description: 'Valuation, dilution, SAFEs vs. priced rounds' },
      { week: 4, title: 'Term Sheet Anatomy', description: 'Pro-rata, liquidation, anti-dilution, board seats' },
      { week: 5, title: 'Due Diligence', description: 'Dataroom prep, legal, IP, cap table clean-up' },
      { week: 6, title: 'Investor Pitch Day', description: 'Live pitches to cohort + invited angel investors' },
    ],
  },
  {
    slug: 'operations-finance',
    name: 'Operations & Finance for Founders',
    description: 'The numbers founders must master: P&L, cash flow, unit economics, pricing strategy, and financial modeling for decisions.',
    track: 'founder',
    duration_min: 120,
    rotation_week: 4,
    day_of_week: 'wed',
    start_time: '14:00',
    space: 'Showroom',
    instructor: 'Apotheos Founder Team',
    capacity: 20,
    objectives: [
      'Read and interpret a P&L and cash flow statement',
      'Calculate and defend unit economics for your business',
      'Build a 12-month financial model',
    ],
    outline: [
      { week: 1, title: 'Financial Literacy', description: 'Income statement, balance sheet, cash flow' },
      { week: 2, title: 'Unit Economics', description: 'CAC, LTV, payback period, cohort analysis' },
      { week: 3, title: 'Pricing Strategy', description: 'Value-based pricing, freemium, tiered SaaS' },
      { week: 4, title: 'Budgeting', description: 'Zero-based budgeting, runway management' },
      { week: 5, title: 'Financial Modeling', description: 'Build a 12-month model in Google Sheets' },
      { week: 6, title: 'CFO Mindset', description: 'When to raise, when to cut, scenarios' },
    ],
  },
  {
    slug: 'leadership-culture',
    name: 'Leadership & Culture Building',
    description: 'Build teams that perform and cultures that last: hiring, management frameworks, conflict resolution, and leading through change.',
    track: 'founder',
    duration_min: 120,
    rotation_week: 5,
    day_of_week: 'thu',
    start_time: '14:00',
    space: 'Showroom',
    instructor: 'Apotheos Founder Team',
    capacity: 25,
    objectives: [
      'Articulate and operationalise your company values',
      'Run high-quality 1:1s, hiring loops, and performance reviews',
      'Navigate conflict and lead through ambiguity',
    ],
    outline: [
      { week: 1, title: 'Leadership Archetypes', description: 'Your leadership style, strengths, blind spots' },
      { week: 2, title: 'Hiring', description: 'Job design, interviewing, offers, onboarding' },
      { week: 3, title: '1:1s & Feedback', description: 'Radical candor, continuous feedback loops' },
      { week: 4, title: 'Culture Systems', description: 'Values, rituals, norms, remote culture' },
      { week: 5, title: 'Conflict & Change', description: 'Conflict resolution, managing layoffs, pivots' },
      { week: 6, title: 'Leadership Manifesto', description: 'Present your personal leadership philosophy' },
    ],
  },
  {
    slug: 'kids-entrepreneurship',
    name: 'Kids Entrepreneurship Club',
    description: 'Young entrepreneurs ages 8–14 learn ideation, pitching, and mini-project execution. Real businesses, real learning, real fun.',
    track: 'founder',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'wed',
    start_time: '15:30',
    space: 'Parlour',
    instructor: 'Apotheos Founder Team',
    capacity: 15,
    objectives: [
      'Develop a simple business idea and validate it',
      'Create a mini pitch deck and present it',
      'Build confidence presenting ideas to an audience',
    ],
    outline: [
      { title: 'Ideas & Problems', description: 'Brainstorm, pain points, simple opportunity spotting' },
      { title: 'Building & Pitching', description: 'Mini product, one-page plan, pitch practice' },
      { title: 'Demo Day', description: 'Kids pitch to parents and community' },
    ],
  },
]

// ─── COMMUNITY / CREATIVE TRACK ───────────────────────────────
const communityCourses: CourseData[] = [
  {
    slug: 'creative-writing-workshop',
    name: 'Creative Writing Workshop',
    description: 'Explore your voice through short fiction, essays, poetry, and journaling. Weekly prompts, peer feedback, and craft discussion.',
    track: 'community',
    duration_min: 120,
    rotation_week: null,
    day_of_week: 'mon',
    start_time: '19:00',
    space: 'Parlour',
    instructor: 'Apotheos Creative Team',
    capacity: 15,
    objectives: [
      'Write 5,000+ words of original work across multiple forms',
      'Give and receive structured peer feedback',
      'Develop a distinct personal writing voice',
    ],
    outline: [
      { title: 'Voice & Form', description: 'Finding your voice, flash fiction, poetry forms' },
      { title: 'Craft', description: 'Show vs. tell, dialogue, scene-setting, revision' },
      { title: 'Publication', description: 'Submitting work, self-publishing, building readership' },
    ],
  },
  {
    slug: 'music-production',
    name: 'Music Production & Sound Design',
    description: 'Learn Ableton Live from scratch: beat-making, sound design, mixing, mastering, and releasing your first track.',
    track: 'community',
    duration_min: 120,
    rotation_week: null,
    day_of_week: 'tue',
    start_time: '19:00',
    space: 'Recording Studio',
    instructor: 'Apotheos Creative Team',
    capacity: 10,
    objectives: [
      'Navigate Ableton Live and produce a complete track',
      'Apply core mixing and mastering techniques',
      'Release original music to a streaming platform',
    ],
    outline: [
      { title: 'DAW Basics', description: 'Ableton interface, MIDI, clips, arrangement view' },
      { title: 'Sound Design', description: 'Synthesis, sampling, effects chains, mixing' },
      { title: 'Mastering & Release', description: 'Loudness, streaming specs, DistroKid' },
    ],
  },
  {
    slug: 'visual-arts-studio',
    name: 'Visual Arts Studio',
    description: 'Open studio time plus structured workshops in painting, drawing, printmaking, and mixed media. Bring your project.',
    track: 'community',
    duration_min: 120,
    rotation_week: null,
    day_of_week: 'wed',
    start_time: '19:00',
    space: 'Art Studio',
    instructor: 'Apotheos Creative Team',
    capacity: 20,
    objectives: [
      'Complete at least one significant artwork per rotation',
      'Experiment with 3+ different media',
      'Develop a personal artistic language',
    ],
    outline: [
      { title: 'Foundations', description: 'Line, form, color theory, composition' },
      { title: 'Media Exploration', description: 'Acrylics, watercolor, printmaking, collage' },
      { title: 'Exhibition', description: 'Group show at the end of each rotation' },
    ],
  },
  {
    slug: 'community-dialogue',
    name: 'Community Dialogue & Philosophy',
    description: 'Structured Socratic discussions on philosophy, ethics, AI, humanity, and the future. No prior philosophy experience required.',
    track: 'community',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'thu',
    start_time: '19:00',
    space: 'Parlour',
    instructor: 'Apotheos Community Team',
    capacity: 20,
    objectives: [
      'Articulate and defend a reasoned philosophical position',
      'Practice active listening and charitable interpretation',
      'Explore the intersection of technology and human values',
    ],
    outline: [
      { title: 'Frameworks', description: 'Intro to Socratic method, logical fallacies, argumentation' },
      { title: 'Topics', description: 'Rotating themes: free will, AI consciousness, justice, meaning' },
      { title: 'Integration', description: 'Personal essay — your examined life' },
    ],
  },
  {
    slug: 'founder-fireside',
    name: 'Founder Fireside Chats',
    description: 'Intimate conversations with successful founders, investors, and builders. Monthly event open to all members.',
    track: 'community',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'fri',
    start_time: '19:00',
    space: 'Event Hall',
    instructor: 'Guest Speakers',
    capacity: 60,
    objectives: [
      'Learn from direct founder experience and hard-won lessons',
      'Build relationships with the broader founder ecosystem',
      'Generate actionable insights for your own journey',
    ],
    outline: [
      { title: 'Interview', description: 'Structured conversation with guest founder (60 min)' },
      { title: 'Networking', description: 'Open mixer with drinks (30 min)' },
    ],
  },
  {
    slug: 'open-mic-performance',
    name: 'Open Mic & Performance Night',
    description: 'Monthly open mic — music, spoken word, comedy, storytelling. A stage for every voice in the community.',
    track: 'community',
    duration_min: 120,
    rotation_week: null,
    day_of_week: 'sat',
    start_time: '19:00',
    space: 'Event Hall',
    instructor: 'Community-Led',
    capacity: 80,
    objectives: [
      'Perform original work in front of a live audience',
      'Build community through shared creative expression',
      'Practice courage and creative risk-taking',
    ],
    outline: [
      { title: 'Sign-Up', description: '5-min slots, all welcome, hosted by community MC' },
      { title: 'Performance', description: 'Open stage (90 min)' },
      { title: 'Encore', description: 'Community jam / collective performance' },
    ],
  },
  {
    slug: 'sunday-integration',
    name: 'Sunday Integration Circle',
    description: 'Weekly community gathering: reflection, shared meals, intention-setting, and connecting around what matters most.',
    track: 'community',
    duration_min: 120,
    rotation_week: null,
    day_of_week: 'sun',
    start_time: '11:00',
    space: 'Event Hall',
    instructor: 'Community-Led',
    capacity: 50,
    objectives: [
      'Develop a personal weekly reflection practice',
      'Strengthen bonds with the Apotheos community',
      'Set clear intentions for the week ahead',
    ],
    outline: [
      { title: 'Reflection', description: 'Guided journaling, gratitude practice, wins & lessons' },
      { title: 'Connection', description: 'Shared meal, informal conversations' },
      { title: 'Intention', description: 'Weekly commitments, accountability pairs' },
    ],
  },
  {
    slug: 'dj-workshop',
    name: 'DJ Workshop',
    description: 'Learn to mix: beatmatching, EQing, transitions, and curation. Work on professional DJ equipment in the recording studio.',
    track: 'community',
    duration_min: 90,
    rotation_week: null,
    day_of_week: 'sat',
    start_time: '14:00',
    space: 'Recording Studio',
    instructor: 'Apotheos Creative Team',
    capacity: 8,
    objectives: [
      'Mix a 30-minute DJ set without audible mistakes',
      'Understand EQing, filtering, and effects in context',
      'Curate and communicate a musical story',
    ],
    outline: [
      { title: 'Equipment & Basics', description: 'CDJs/turntables, mixer, beatmatching' },
      { title: 'Transitions & EQ', description: 'Phrasing, frequency blending, drops' },
      { title: 'Set Building', description: 'Energy arcs, curation, live recording' },
    ],
  },
]

// ─── MASTER CATALOGUE ─────────────────────────────────────────
export const ALL_COURSES: CourseData[] = [
  ...wellnessCourses,
  ...aiCourses,
  ...founderCourses,
  ...communityCourses,
]

export const COURSES_BY_SLUG = Object.fromEntries(ALL_COURSES.map(c => [c.slug, c]))

export const COURSES_BY_TRACK: Record<TrackName, CourseData[]> = {
  wellness: wellnessCourses,
  ai: aiCourses,
  founder: founderCourses,
  community: communityCourses,
}

export const TRACK_META: Record<TrackName, { label: string; icon: string; description: string; color: string }> = {
  wellness: {
    label: 'Wellness',
    icon: '◎',
    description: 'Body, mind & spirit practices rooted in movement, breathwork, nutrition and recovery.',
    color: 'var(--gold)',
  },
  ai: {
    label: 'AI Learning',
    icon: '⬡',
    description: 'Practical AI literacy and technical skills for builders, leaders and founders.',
    color: 'var(--teal-lt)',
  },
  founder: {
    label: 'Founder Ecosystem',
    icon: '◈',
    description: 'End-to-end startup and business education from ideation to fundraising.',
    color: 'var(--rust-lt)',
  },
  community: {
    label: 'Community & Arts',
    icon: '◉',
    description: 'Creative expression, dialogue, performance and shared culture.',
    color: 'var(--sage-lt)',
  },
}
